version: '3.8'
services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: assingmentDB
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - my-network

  my-dotnet-app:
    image: mywebapi
    container_name: assingmentAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80" 
    command: dotnet ef database update
    depends_on:
      - mysql
    networks:
      - my-network

# networks:
#   my-network:
#     driver: bridge
