version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: assingmentDB
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
      - ConnectionStrings__DefaultConnection="Server=mysql;Port=3306;Database=Users;User=root;Password=password;"
    networks:
      - my-network

  my-dotnet-app:
    image: mywebapi
    container_name: assingmentAPI
    ports:
      - "80:80" #- "8080:80"  # Map host port 8080 to container port 80
    depends_on:
      - mysql
    networks:
      - my-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection="Server=13.237.137.147;Port=3306;Database=Users;User=tnt;Password=tnt@odds;"

networks:
  my-network:
    driver: bridge
