services:
  my-dotnet-app:
    image: mywebapi
    build: ./
    container_name: assingmentAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Server=13.237.137.147; Database=Users; User ID=tnt3; Password=tntatodds
    ports:
      - "8888:8080"
