version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: assingmentDB
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - my-network

  my-dotnet-app:
    image: mywebapi
    container_name: assingmentAPI
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
